[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_DISABLE_ESLINT = "1"

# Configuraci칩n para redireccionar p치ginas no encontradas a la p치gina 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

# Configuraci칩n para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
