[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_DISABLE_ESLINT = "1"

# Configuración para ignorar advertencias de secretos expuestos
# Esto es necesario porque usamos variables NEXT_PUBLIC_ que son intencionalmente públicas
[build.processing.secrets]
  # Marcar las claves públicas como seguras para exposición
  allowed = ["NEXT_PUBLIC_*"]

# Configuración para redireccionar páginas no encontradas a la página 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

# Configuración para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
